server:
  # 服务器的HTTP端口，默认为8080
  port: 81
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    
# Spring配置
spring:
  mvc:
    favicon:
      enabled: false
  profiles:    active: druid,mongo,redis,hibernate,constant,monitor
  # 及时刷新
  thymeleaf:
    cache: false
    
# 日志配置
logging:
  level:
    com.peiqi: debug
    org.springframework: warn

  #JSP支持
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
  
